import usbtmc
import time

instr =  usbtmc.Instrument(6833, 1416)
print("Informacije o osciloskopu:")
print("IDN : " + str(instr.ask("*IDN?")))
print("Channel1 settings:")
print("DISP = " + str(instr.ask(":CHAN1:DISP?")))
print("COUP = " + str(instr.ask(":CHAN1:COUP?")))
print("PROB = " + str(instr.ask(":CHAN1:PROB?")))
print("SCAL = " + str(instr.ask(":CHAN1:SCAL?")))
print("OFFS = " + str(instr.ask(":CHAN1:OFFS?")))
print("Channel2 settings:")
print("DISP = " + str(instr.ask(":CHAN2:DISP?")))
print("COUP = " + str(instr.ask(":CHAN2:COUP?")))
print("PROB = " + str(instr.ask(":CHAN2:PROB?")))
print("SCAL = " + str(instr.ask(":CHAN2:SCAL?")))
print("OFFS = " + str(instr.ask(":CHAN2:OFFS?")))
print("Time settings:")
print("MODE = " + str(instr.ask(":TIM:MODE?")))
print("OFFS = " + str(instr.ask(":TIM:OFFS?")))
print("SCAL = " + str(instr.ask(":TIM:SCAL?")))
print("FORMAT = " + str(instr.ask(":TIM:FORM?")))
print("Trigger settings:")
print("STAT = " + str(instr.ask(":TRIG:STAT?")))
print("MODE = " + str(instr.ask(":TRIG:MODE?")))
print("SOUR = " + str(instr.ask(":TRIG:EDGE:SOUR?")))
print("SWE  = " + str(instr.ask(":TRIG:EDGE:SWE?")))
print("COUP = " + str(instr.ask(":TRIG:EDGE:COUP?")))
print("LEV  = " + str(instr.ask(":TRIG:EDGE:LEV?")))
print("SLOP = " + str(instr.ask(":TRIG:EDGE:SLOP?")))
print("SENS = " + str(instr.ask(":TRIG:EDGE:SENS?")))